# Project Euler problem 002: Even Fibonacci numbers
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Run at: http://coffeescript.org/#try:%23%20paste%20code%20here

# O(n)
euler002 = (max) ->
  even = 2
  other1 = 3
  other2 = 5
  sum = 0

  while (even <= 4000000)
    sum += even
    even = other1 + other2
    other1 = other2 + even
    other2 = even + other1

  sum

console.log(euler002(4000000))
